[package]
name = "client"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only or MPL-2.0"

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
axum = "0.7.5"
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full", "signal"] }
